package com.aeropelican.notificationservice.service;

import com.aeropelican.notificationservice.dto.request.UpdateTemplateRequestDTO;
import com.aeropelican.notificationservice.dto.request.UpdateTemplateStatusRequestDTO;
import com.aeropelican.notificationservice.dto.response.TemplateResponseDTO;
import com.aeropelican.notificationservice.entity.NotificationTemplate;
import com.aeropelican.notificationservice.exception.TemplateNotFoundException;
import com.aeropelican.notificationservice.repository.NotificationTemplateRepository;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDateTime;

@Service
public class NotificationTemplateService {

    private final NotificationTemplateRepository templateRepository;

    public NotificationTemplateService(NotificationTemplateRepository templateRepository) {
        this.templateRepository = templateRepository;
    }

    // P11: Update Template & Channel Contents
    @Transactional
    public TemplateResponseDTO updateTemplate(Long id, UpdateTemplateRequestDTO request) {
        NotificationTemplate template = templateRepository.findById(id)
                .orElseThrow(() -> new TemplateNotFoundException("Template not found with ID: " + id));

        // Use templateCode since entity does not have a 'name' field
        if (request.getName() != null) {
            template.setTemplateCode(request.getName());
        }
        template.setDescription(request.getDescription());
        template.setUpdatedAt(LocalDateTime.now());

        NotificationTemplate updatedTemplate = templateRepository.save(template);
        return mapToResponseDTO(updatedTemplate);
    }

    // P12: Update Active/Inactive Status
    @Transactional
    public TemplateResponseDTO updateTemplateStatus(Long id, UpdateTemplateStatusRequestDTO request) {
        NotificationTemplate template = templateRepository.findById(id)
                .orElseThrow(() -> new TemplateNotFoundException("Template not found with ID: " + id));

        if (request.getActive() != null) {
            template.setActive(request.getActive());
        }
        template.setUpdatedAt(LocalDateTime.now());

        NotificationTemplate updatedTemplate = templateRepository.save(template);
        return mapToResponseDTO(updatedTemplate);
    }

    private TemplateResponseDTO mapToResponseDTO(NotificationTemplate template) {
        TemplateResponseDTO dto = new TemplateResponseDTO();
        dto.setId(template.getId());
        dto.setName(template.getTemplateCode());
        dto.setDescription(template.getDescription());
        dto.setActive(template.isActive()); // Use isActive() for primitive boolean generated by Lombok
        return dto;
    }
}